FROM node:20-bookworm-slim AS build

WORKDIR /app

COPY package*.json /app/
RUN npm install

COPY . /app
RUN npm run build

FROM nginx:1.27-alpine

RUN apk add --no-cache gettext
COPY nginx.railway.conf /etc/nginx/templates/default.conf.template
COPY --from=build /app/dist /usr/share/nginx/html
