FROM node:20-bookworm-slim AS build

WORKDIR /app

COPY package*.json /app/
RUN npm install

COPY . /app
RUN npm run build

FROM caddy:2

COPY Caddyfile.railway /etc/caddy/Caddyfile
COPY --from=build /app/dist /srv
